# Copyright (c) 2014-2015 Software Architecture Group (Hasso Plattner Institute)
# Copyright (c) 2015 Fabio Niephaus, Google Inc.

language: smalltalk
sudo: false

os:
  - linux
  - osx

smalltalk:
  - Squeak-trunk
  - Squeak-5.1

after_success: bash $TRAVIS_BUILD_DIR/scripts/prepare_image.sh
