# Copyright (c) 2014-2015 Software Architecture Group (Hasso Plattner Institute)
# Copyright (c) 2015 Fabio Niephaus, Google Inc.

language: smalltalk
sudo: false

os:
  - linux
  - osx

smalltalk:
  - Squeak-trunk
  - Squeak-5.0
  - Squeak-4.6

after_success:
  - chmod +x $PROJECT_HOME/scripts/prepare_image.sh
  - $PROJECT_HOME/scripts/prepare_image.sh
