# Copyright (c) 2014-2015 Software Architecture Group (Hasso Plattner Institute)
# Copyright (c) 2015 Fabio Niephaus, Google Inc.

language: smalltalk
sudo: false

os:
  - linux
  - osx

smalltalk:
  - Squeak-trunk
  - Squeak-5.1
  - Squeak-5.0
  - Squeak-4.6

matrix:
  allow_failures:
    - smalltalk: Squeak-5.0
    - smalltalk: Squeak-4.6
  fast_finish: true

after_success: bash $TRAVIS_BUILD_DIR/scripts/prepare_image.sh
