# Copyright (c) 2014-2015 Software Architecture Group (Hasso Plattner Institute)
# Copyright (c) 2015 Fabio Niephaus, Google Inc.

language: smalltalk
sudo: false

smalltalk:
  - SqueakTrunk
  - Squeak5.0
  - Squeak4.6

env:
  - BASELINE=Vivide
  - PACKAGES="/repository"

after_success:
  - chmod +x $PROJECT_HOME/scripts/prepare_image.sh
  - $PROJECT_HOME/scripts/prepare_image.sh